USE [master]
GO

/****** Object:  Database [Contacts]    Script Date: 22/01/2023 13:37:02 ******/
CREATE DATABASE [Contacts]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Contacts', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Contacts.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Contacts_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Contacts_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Contacts].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Contacts] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Contacts] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Contacts] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Contacts] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Contacts] SET ARITHABORT OFF 
GO

ALTER DATABASE [Contacts] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Contacts] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Contacts] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Contacts] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Contacts] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Contacts] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Contacts] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Contacts] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Contacts] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Contacts] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Contacts] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Contacts] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Contacts] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Contacts] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Contacts] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Contacts] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Contacts] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Contacts] SET RECOVERY FULL 
GO

ALTER DATABASE [Contacts] SET  MULTI_USER 
GO

ALTER DATABASE [Contacts] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Contacts] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Contacts] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Contacts] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Contacts] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Contacts] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Contacts] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Contacts] SET  READ_WRITE 
GO



--Script to create table

USE [Contacts]
GO

/****** Object:  Table [dbo].[Contacts]    Script Date: 22/01/2023 12:23:39 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Contacts](
	[ContactID] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [varchar](20) NULL,
	[LastName] [varchar](20) NULL,
	[PhoneNumber] [varchar](15) NULL,
 CONSTRAINT [PK_Contacts] PRIMARY KEY CLUSTERED 
(
	[ContactID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO




--Script to create SPs

USE [Contacts]
GO

/****** Object:  StoredProcedure [dbo].[SPAddContactsData]    Script Date: 22/01/2023 12:24:09 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[SPAddContactsData] @FirstName VARCHAR(20)
	,@LastName VARCHAR(20)
	,@PhoneNumber VARCHAR(15)
	WITH RECOMPILE
AS
BEGIN
	INSERT INTO Contacts (
		FirstName
		,LastName
		,PhoneNumber
		)
	VALUES (
		@FirstName
		,@LastName
		,@PhoneNumber
		)
END
GO


USE [Contacts]
GO

/****** Object:  StoredProcedure [dbo].[SPDeleteContactsData]    Script Date: 22/01/2023 12:24:25 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[SPDeleteContactsData] @ContactID INT
	WITH RECOMPILE
AS
BEGIN
	DELETE
	FROM Contacts
	WHERE ContactID = @ContactID
END
GO


USE [Contacts]
GO

/****** Object:  StoredProcedure [dbo].[SPGetContactsData]    Script Date: 22/01/2023 12:24:38 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[SPGetContactsData]
	WITH RECOMPILE
AS
BEGIN
	SELECT *
	FROM Contacts
	ORDER BY FirstName
END
GO


USE [Contacts]
GO

/****** Object:  StoredProcedure [dbo].[SPGetContactsDataByID]    Script Date: 22/01/2023 12:25:03 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[SPGetContactsDataByID] @ContactID INT
	WITH RECOMPILE
AS
BEGIN
	SELECT *
	FROM Contacts
	WHERE ContactID = @ContactID
END
GO


USE [Contacts]
GO

/****** Object:  StoredProcedure [dbo].[SPUpdateContactsData]    Script Date: 22/01/2023 12:25:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[SPUpdateContactsData] @ContactID INT
	,@FirstName VARCHAR(20)
	,@LastName VARCHAR(20)
	,@PhoneNumber VARCHAR(15)
	WITH RECOMPILE
AS
BEGIN
	UPDATE Contacts
	SET FirstName = @FirstName
		,LastName = @LastName
		,PhoneNumber = @PhoneNumber
	WHERE ContactID = @ContactID
END
GO


